name: 'GitHub Actions CSU Auto Attendance'
 
on:
  push:
  schedule:
  # 定时任务，在每天的5,6,7点定时自动健康打卡
    - cron: '0 21,22,23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install requirments
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute code
      run: |
        python attend.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }}
